conf/layer.conf
Added `zeus` to LAYERSERIES_COMPAT
=> Add zeus to LAYERSERIES_COMPAT

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Engine: 9d517f475ba1282b619477bde8e708d6a34287cf
SDK: https://github.com/flutter/flutter/releases/tag/2.3.0-24.1.pre
=> Update default engine version 06/30/2021

recipes-graphics/flutter-engine/flutter-engine.bb
Bitbake doesn't allows to mix comments and code on the same line, so this PR is to place the comment on it's own line
=> Fix: parse error in flutter-engine.bb

recipes-graphics/flutter-embedded-linux/flutter-drm-eglstream-backend.bb, recipes-graphics/flutter-embedded-linux/flutter-drm-eglstream-so.bb, recipes-graphics/flutter-embedded-linux/flutter-drm-gbm-backend.bb, recipes-graphics/flutter-embedded-linux/flutter-drm-gbm-so.bb, recipes-graphics/flutter-embedded-linux/flutter-wayland-client.bb, recipes-graphics/flutter-embedded-linux/flutter-wayland-so.bb
I added new recipe files to build .so files for flutter tools for eLinux.
=> Add so file build

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
See: https://github.com/sony/flutter-embedded-linux/releases/tag/fbeb7e22bd
=> Upgrade to flutter 2.5.0-5.1.pre

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
See: https://github.com/sony/flutter-embedded-linux/releases/tag/7a4c4505f6
=> [Release] Flutter 2.5.0-5.2.pre

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
See: https://github.com/sony/flutter-embedded-linux/releases/tag/fcde2c8b2f
=> Upgrade to flutter-2.5.0-5.3.pre

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
I switched from beta channel to stable channel. https://github.com/sony/meta-flutter/issues/16
See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/f0826da7ef
- https://github.com/flutter/flutter/tree/2.5.0
=> Upgrade to flutter-2.5.0 (stable channel)

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Upgraded to the flutter 2.5.1. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/b3af521a05
- https://github.com/flutter/flutter/tree/2.5.1
=> Upgrade to flutter-2.5.1

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Upgraded to the flutter 2.5.2. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/6ac856380f
- https://github.com/flutter/flutter/tree/2.5.2
=> Upgrade to flutter 2.5.2

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.8.0. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/40a99c5951
- https://github.com/flutter/flutter/tree/2.8.0
=> Update to flutter-2.8.0

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.8.1. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/890a5fca2e
- https://github.com/flutter/flutter/tree/2.8.1
=> Update to flutter-2.8.1

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.10.0. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/776efd2034
- https://github.com/flutter/flutter/tree/2.10.0
=> Update to flutter-2.10.0

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.10.1. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/ab46186b24
- https://github.com/flutter/flutter/tree/2.10.1
=> flutter stable 2.10.1

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.10.3. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/bd539267b4
- https://github.com/flutter/flutter/tree/2.10.3
=> flutter stable version 2.10.3

README.md, recipes-graphics/flutter-embedded-linux/repository.inc, recipes-graphics/flutter-engine/flutter-engine.bb
Updated to the flutter 2.10.4. See also:
- https://github.com/sony/flutter-embedded-linux/releases/tag/57d3bac3dd
- https://github.com/flutter/flutter/tree/2.10.4
=> Update for flutter 2.10.4

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
Signed-off-by: Hidenori.Matsubayashi <hidenori.matsubayashi@gmail.com>
cc @taka-okayama
=> Update for flutter 2.10.5 (flutter/engine is the same version as 2.10.4)

README.md, recipes-graphics/flutter-embedded-linux/repository.inc, recipes-graphics/flutter-engine/flutter-engine.bb
Signed-off-by: Hidenori.Matsubayashi <hidenori.matsubayashi@gmail.com>
=> Update for flutter 3.0.0

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
See:
- https://github.com/sony/flutter-embedded-linux/releases/tag/caaafc5604
- https://github.com/flutter/flutter/tree/3.0.1
Signed-off-by: Hidenori.Matsubayashi <hidenori.matsubayashi@gmail.com>
=> Update for flutter 3.0.1

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
=> Update for flutter 3.0.2

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
=> Update for flutter 3.0.3

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
=> Update for flutter 3.0.4

README.md, recipes-graphics/flutter-engine/flutter-engine.bb
=> Update for flutter 3.0.5

AUTHORS, README.md, conf/flutter-engine.conf, conf/layer.conf, recipes-graphics/depot-tools-native/depot-tools-native.bb, recipes-graphics/flutter-embedded-linux/dependency.inc, recipes-graphics/flutter-embedded-linux/flutter-drm-eglstream-so.bb, recipes-graphics/flutter-embedded-linux/flutter-drm-gbm-so.bb, recipes-graphics/flutter-embedded-linux/flutter-wayland-so.bb, recipes-graphics/flutter-embedded-linux/repository.inc, recipes-graphics/flutter-embedded-linux/tasks.inc, recipes-graphics/flutter-engine/flutter-engine.bb
=> Add kirkstone support

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.3.0

README.md, conf/flutter-engine.conf
=> Update for flutter 3.3.1

recipes-graphics/flutter-engine/flutter-engine.bb
=> Add "--enable-fontconfig" option for engine compilation

README.md, conf/flutter-engine.conf
=> Update for flutter-3.3.2

README.md, conf/flutter-engine.conf
=> Update for flutter 3.3.3 release

README.md, conf/flutter-engine.conf
=> Update for flutter 3.3.4

README.md, conf/flutter-engine.conf
=> Update for flutter 3.3.5

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.3.7

AUTHORS, recipes-graphics/flutter-engine/flutter-engine.bb
Fixes https://github.com/sony/meta-flutter/issues/60
=> fix: make populate_lic task depend on configure task to fetch src prior to checksum

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.3.9

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.3.10

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.7.0

README.md, conf/flutter-engine.conf
=> Update for flutter 3.7.1

README.md, conf/flutter-engine.conf, recipes-graphics/flutter-embedded-linux/repository.inc
=> Update for flutter 3.7.2

README.md, conf/flutter-engine.conf
=> Update for flutter 3.7.3

README.md
=> readme: fix syntax expires in DRM-GBM backend

recipes-graphics/flutter-embedded-linux/repository.inc
https://github.com/sony/flutter-embedded-linux/commit/589c117b73e56de30a907ae3b4498724ae32d75a
=> embedder: update SRCREV to the latest version

recipes-graphics/flutter-embedded-linux/tasks.inc
=> embedder: fix warnings on tasks.inc

recipes-graphics/flutter-embedded-linux/repository.inc
This change updates the revision of flutter-embedded-linux to the latest version.
=> update srcrev of flutter-embedded-linux
